#!/bin/sh

if [ -z "$1" ]; then
    param="main"
else
    param="$1"
fi

if [ ! -x "$param" ]; then
    echo "Nothing to debug! ( no executable nor param given )"
    exit 1
fi

valgrind \
-v \
--tool=memcheck \
--log-file=test_world-valgrind-`date +%F_%R`.log \
--leak-check=yes \
--error-limit=no \
--demangle=yes \
--num-callers=20 \
--track-fds=yes \
--trace-children=yes \
--show-reachable=yes \
./"$param" "$@"

