#! /bin/bash
#g++ serialization_test.cpp -L.. -lboost_serialization -lcharacter -lsoul -lcoordinates -o test_serialization_1
echo "Serialization tests.."
g++ serialization_test_2.cpp -L.. -lboost_serialization -lcoordinates -litem -lsoul -lcoordinates -lcharacter -o test_serialization_2
echo "sha-1 generation tests.."
g++ sha1_speed_test.cpp -L.. -l hl-sha -o test_sha1_speed -lboost_thread

