#!/bin/sh

#    --trace-malloc=yes \

valgrind \
   -v \
   --tool=memcheck \
   --log-file=test_serialization2-valgrind-`date +%F_%R`.log \
    --leak-check=yes \
    --error-limit=no \
    --demangle=yes \
    --num-callers=20 \
	--track-fds=yes \
	--trace-children=yes \
	--show-reachable=yes \
   ./test_thread_synchronization_2 "$@"

